import React, { useState } from 'react';
import { ShieldCheck, Key, Loader2 } from 'lucide-react';
import Modal from '@/components/modals/modal';
import Input from '@/components/ui/input';
import Button from '@/components/ui/button';

interface TwoFactorModalProps {
    isOpen: boolean;
    onClose: () => void;
    onSuccess: () => void;
}

export default function TwoFactorModal({ isOpen, onClose, onSuccess }: TwoFactorModalProps) {
    const [otpInput, setOtpInput] = useState('');
    const [isVerifying, setIsVerifying] = useState(false);
    const [otpError, setOtpError] = useState('');

    const handleVerify = (e: React.FormEvent) => {
        e.preventDefault();
        if (otpInput.length < 6) {
            setOtpError('Please enter a valid 6-digit verification code.');
            return;
        }

        setIsVerifying(true);
        setOtpError('');

        setTimeout(() => {
            setIsVerifying(false);
            onClose();
            onSuccess();
        }, 600);
    };

    return (
        <Modal
            isOpen={isOpen}
            onClose={onClose}
            size="md"
            title={
                <div className="flex items-center gap-2.5">
                    <div className="w-8 h-8 rounded-lg bg-orange-100 dark:bg-orange-950/50 text-[#FF4A1F] flex items-center justify-center shrink-0">
                        <ShieldCheck size={18} />
                    </div>
                    <div>
                        <h3 className="text-sm font-bold text-slate-900 dark:text-slate-100">
                            Two-Factor Authentication
                        </h3>
                        <p className="text-[11px] text-slate-500 dark:text-slate-400 font-normal">
                            Enter 6-digit verification code from your Authenticator app
                        </p>
                    </div>
                </div>
            }
        >
            <form onSubmit={handleVerify} className="space-y-4 font-sans">
                {otpError && (
                    <div className="p-2.5 bg-red-50 dark:bg-red-950/40 border border-red-200 dark:border-red-800 text-xs font-medium text-red-600 dark:text-red-400 rounded-lg text-center">
                        {otpError}
                    </div>
                )}

                <div className="bg-slate-50 dark:bg-[#1e2329] p-3 rounded-md border border-slate-200 dark:border-slate-700 text-center space-y-2">
                    <p className="text-xs text-slate-600 dark:text-slate-300 font-medium">
                        Enter the 6-digit TOTP code generated by{' '}
                        <strong className="text-slate-900 dark:text-white">Google Authenticator</strong> or{' '}
                        <strong className="text-slate-900 dark:text-white">Authy</strong>.
                    </p>
                </div>

                <div>
                    <label className="text-xs font-bold text-slate-700 dark:text-slate-300 block mb-1">
                        6-Digit Verification Code *
                    </label>
                    <Input
                        type="text"
                        maxLength={6}
                        value={otpInput}
                        onChange={(e) => {
                            setOtpInput(e.target.value.replace(/\D/g, ''));
                            setOtpError('');
                        }}
                        placeholder="e.g. 492018"
                        className="text-center font-mono tracking-widest text-base font-bold h-10"
                        required
                    />
                </div>

                <Button
                    type="submit"
                    disabled={isVerifying || otpInput.length < 6}
                    className="w-full h-10 text-xs font-bold bg-[#FF4A1F] hover:bg-[#e03e15] text-white shadow-md cursor-pointer flex items-center justify-center gap-1.5"
                >
                    {isVerifying ? <Loader2 size={16} className="animate-spin" /> : <Key size={15} />}
                    <span>{isVerifying ? 'Verifying Code…' : 'Verify & Complete Sign In'}</span>
                </Button>
            </form>
        </Modal>
    );
}
