export type PODFilterTab = 'all' | 'needs_upload' | 'in_review' | 'approved' | 'rejected';

export interface PODOrderItem {
    id: string | number;
    rawId?: string | number;
    slug?: string;
    order_id?: string;
    order_no?: string;
    order_number?: string;
    customer_name?: string;
    customer_avatar?: string;
    customer_phone?: string;
    customer_email?: string;
    customer_company?: string;
    customer_rating?: number | string;
    customer_verified?: boolean;
    customer?: {
        id?: string | number;
        name?: string;
        company_name?: string;
        profile_picture?: string;
        avatar?: string;
        rating?: number | string;
        is_verified?: boolean;
        completed_orders?: number | string;
        phone?: string;
        email?: string;
    };
    route?: string;
    pickup_city?: string;
    pickup_address?: string;
    delivery_city?: string;
    delivery_address?: string;
    vehicle?: string;
    vehicle_type?: string;
    vehicle_plate?: string;
    weight?: string | number;
    cargo_weight?: string | number;
    total_weight?: string | number;
    pallets?: string;
    type_of_pallets?: string;
    load_type?: string;
    driver?: string;
    driver_name?: string;
    driver_phone?: string;
    pickup_date?: string;
    delivery_date?: string;
    amount?: string | number;
    total_amount?: string | number;
    amount_raw?: number;
    status?: string;
    status_raw?: string;
    pod_status: 'Not Uploaded' | 'Pending Review' | 'Approved' | 'Rejected';
    pod_status_raw?: string;
    pod_document_url?: string;
    pod_file_url?: string;
    pod_file_name?: string;
    pod_uploaded_at?: string;
    has_pod: boolean;
}
