export type OrderFilterTab = 'all' | 'in_transit' | 'pod_review' | 'completed' | 'cancelled';

export interface CustomerOrderItem {
    id: string | number;
    rawId?: string | number;
    order_id?: string;
    order_number?: string;
    quote_id?: string | number;
    quote_request_id?: string | number;
    created_at?: string;
    date?: string;
    order_date?: string;
    pickup_date?: string;
    delivery_date?: string;
    estimated_delivery?: string;
    estimated_time?: string;
    eta?: string;
    route?: string;
    pickup_city?: string;
    pickup_address?: string;
    delivery_city?: string;
    delivery_address?: string;
    supplier_name?: string;
    supplier_avatar?: string;
    carrier_name?: string;
    carrier_avatar?: string;
    supplier?: {
        id?: string | number;
        name?: string;
        company_name?: string;
        profile_picture?: string;
        avatar?: string;
        rating?: number | string;
        is_verified?: boolean;
        completed_orders?: number | string;
        phone?: string;
        email?: string;
    };
    rating?: number | string;
    vehicle?: string;
    vehicle_type?: string;
    truck_type?: string;
    vehicle_plate?: string;
    weight?: string | number;
    cargo_weight?: string | number;
    type_of_pallets?: string;
    pallets?: string;
    amount?: string | number;
    total_amount?: string | number;
    amount_raw?: number;
    payment_status?: string;
    status?: string;
    status_raw?: string;
    pod_status?: string;
    pod_document_url?: string;
    pod_file_name?: string;
    is_rated?: boolean;
    customer_review?: any;
    current_location?: string;
    checkpoint?: string;
}
